### ISSUE TITLE
No counter for nucleotide while it's here

### ISSUE THREAD

**Issue by PolinaBevad** [epam/NGB#131]
Hello!
I use NGB in jar (version catgenome-2.5.1.374.1.jar).
For my dataset I have a situation, when counter in BAM string doesn't increase for some nucleotides, but they are in the reads on this position.
Example is on the screenshot: for position 100551144 we have G nucleotide in one read (and in 4 more reads below, if scroll screen), but count for G is 0.
[Settings]-[Alignment]-[Coverage Options] was set to 99 and 100% for testing purpose, but it still repeats. 
How can it be fixed? Any other settings?

Thank you.

![no count for g](https://user-images.githubusercontent.com/32058078/34152921-43fc1be2-e4c1-11e7-9adb-2d2d1710b564.png)

**Comment by mzueva** [comment]
Hi @PolinaBevad ! Thank you for your comment. It looks like 'G' and 'A' nucleotides on this screenshot belong to softclipped read end and such bases aren't included into total count, since they are not aligned to these reference coordinates. Could you please check your reads and verify that these are really softclipped bases? Thank you in advance.

**Comment by PolinaBevad** [comment]
Hi, @mzueva ! 
Yes, they are really softclipped at this region. Thanks for this information!
