### ISSUE TITLE
Protein 3D structure is not shown

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#373]
Protein 3D structure is not shown due to broken integration with `http://www.rcsb.org/`. RCSB is no longer supporting API which was used for this integration: [Legacy API Shutdown](http://www.rcsb.org/news?year=2020&article=5fc9176809ae2a096d081e28). We need to rewrite correspoding code to use new [RCSB API](http://search.rcsb.org/#search-api).

**Comment by Sergeev-Ilya** [comment]
During migrating to the new API, I have faced a small understanding problem.

In previous API, a special link was used to build a request:
http://www.rcsb.org/pdb/rest/customReport?pdbids=1JM7&format=xml&customReportColumns=structureTitle,expressionHost,classification,compound,uniprotRecommendedName

So here we have 5 parameters, which we were waiting from API:
_1) structureTitle
2) expressionHost
3) classification
4) compound
5) uniprotRecommendedName_

==============================================================

According to the previous API , we know, that out Java-object needs such properties from response as:
For dimEntity:

_1. structureId
2. compound
3. chainId
4. uniprotRecommendedName_

For dimStructure:

_5. structureTitle
6. classification_

===============================================================

Also we have the lack of old API documentation. That's why I have a problem with matching old-named parameters and the new ones.

So, my query consists of:
![image](https://user-images.githubusercontent.com/57319975/108352865-827d2600-71f8-11eb-9bb7-8f1e27ecf348.png)

=======================================================

As you can see, I put some numbers on a pic. So I have matched the properties this way:

1. _entry.struct.title_ ---> is **structureTitle** (obviously ^^)
2. _entry.struct_keywords.pdbx_keywords_ ---> I think it is a **classification**.

in entry.polymer_entities:

3. _entity_poly.rcsb_entity_polymer_type_ ---> I think it is a **compound**. I'm not sure.
4. _rcsb_polymer_entity.pdbx_description_ ---> it is definitely a **uniportRecommendedName**, as it shows the same as uniprots.   rcsb_uniprot_protein.name.value does.
5. _rcsb_id_ ---> it is obviously a **stuctureId**.
6. _rcsb_polymer_entity_container_identifiers.auth_asym_ids_ ---> I think is a **chainId**. I'm not sure.

=======================================

So it would be grateful, if I somehow will be informed whether I am correct or not.

**Comment by Sergeev-Ilya** [comment]
Also, I would like to inform about another query.
http://www.rcsb.org/pdb/rest/das/pdb_uniprot_mapping/alignment?query="4HH8"

Here we want to get such structure:
- a list of **Alignments**
- - **Alignment** consists of a list of **PdbBlocks**
- - - **PdbBlock** consists of a list of **Segments**
- - - - **Segment** has 3 properties: _intObjectId, start, end_.

===============================================

So, the only query, which can be mapped to this structure is:

![image](https://user-images.githubusercontent.com/57319975/108588400-0efb2600-736a-11eb-9726-1b0fb98da826.png)

===============================================

As you can see, I have put some numbers on a pic.
1. **Sergment**
2. **PdbBlock**
3. **Alignment**
4. **List of Alignments**

Am I right?

===============================================

Also, some segments have null end coordinates:

![image](https://user-images.githubusercontent.com/57319975/108588424-2d612180-736a-11eb-8cc1-a3befc650574.png)


===============================================

Does this mean, that an object **is just a spot**, not a line?

And how should I design this data - a) should I **put null** to object property, b) or should I **use empty String** "", c) or should it have **the same value**, as start coordinates?

**Comment by mzueva** [comment]
fixed
