### ISSUE TITLE
Incorrect display of highlighting in the bubbles

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#407]
**Describe the bug**
Incorrect display of highlighting in the bubbles (#391 )

**Prerequisites**
 - dataset = dm6_data, .vcf = agnX1.09-28.trim.dm606.realign.vcf
 -  **Bubbles** profile in interest_profiles.json file:
` "Bubbles": {
  "is_default": true,
    "conditions": [
      {
        "highlight_color": "ff0000",
        "condition": "MQRankSum  == -9.612"
      },
      {
        "highlight_color": "008000",
        "condition": "BaseQRankSum  == -3.191"
      },
      {
        "highlight_color": "add8e6",
        "condition": "MQ == 86.87"
      }
]
},`
<p style="margin-top: 0px; margin-bottom: 16px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;Segoe UI&quot;, Arial, freesans, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(0, 0, 0);">Colors of variations</strong></p>
Position Chr X | Color
-- | --
12585001 | ff0000 (red)
12585008 | 008000 (green)
12585016 | add8e6 (light-blue)

**To Reproduce**
1. Go to 'NGB'
2. Go to **Datasets** tab
3. Select dataset and vcf file from **Prerequisites**
4. Find Variation on Position  **chr X:12585001**
5. Click on variation with Position **chr X:12585001**
6. Select 'Collapsed' view
7. Zoom out the track (click '-' button) until a bubble with a 3 number inside appears (~6.2Kbp)
8. Zoom out the track (click '-' button) until a bubble with a 5 number inside appears (~7.7Kbp)
9. Zoom out the track (click '-' button) until a bubble with a 5 number inside appears (~14.5Kbp)
10. Zoom out the track (click '-' button) until a bubble with a 7 number inside appears (~44.4Kbp)

**Expected behavior**
The bubble is highlighted with all 3 colors of variations (red, green, light-blue) and colorless part , evenly distributing the colors like a pie for 7-10 steps

**Actual behavior for the particular step**
7. The bubble with a 3 number inside(~6.2Kbp) **is highlighted in light-blue** color 
8. The bubble with a 5 number inside(~7.7Kbp) **is partially highlighted in light-blue color** 
9. The bubble with a 5 number inside(~14.5Kbp) **isn't highlighted any color** 
10. The bubble with a 7 number inside(~44.4Kbp) **is partially highlighted in red color** 

**Screenshots**
![2021-05-18_16h35_57](https://user-images.githubusercontent.com/83421565/118670157-072f0e80-b7ff-11eb-848e-f5aed92c4244.gif)
![image](https://user-images.githubusercontent.com/83421565/118667360-a0a8f100-b7fc-11eb-8742-94204df384c7.png)
![image](https://user-images.githubusercontent.com/83421565/118667554-ca621800-b7fc-11eb-8239-393dfb0cf62a.png)
![image](https://user-images.githubusercontent.com/83421565/118664921-8c63f480-b7fa-11eb-8684-fa0e939a49cb.png)
![image](https://user-images.githubusercontent.com/83421565/118665457-00060180-b7fb-11eb-9233-bedc81d971ab.png)

**Environment:**
 - NGB version: 2.6.1.2300
 - Browser: Chrome (version 90.0.4430.93)

**Comment by rodichenko** [comment]
@Tatyana2022 @mzueva partially fixed by 5ad8352cd311dbb2423c93ce01d9afb5383c8037.

Since we have both *server*- and *client*- side logic for "collapsing" variants into statistics (aka "bubbles"), behavior of those "bubbles" may differ:
- for *client*-side processing we do know each variant of the bubble and its highlighting info (i.e. `info` fields);
- for *server*-side processing we got already joined variants without* highlighting info.

For your scenario:

> **Actual behavior for the particular step**
> 7. The bubble with a 3 number inside(~6.2Kbp) **is highlighted in light-blue** color
> 8. The bubble with a 5 number inside(~7.7Kbp) **is partially highlighted in light-blue** color
> 9. The bubble with a 5 number inside(~14.5Kbp) **isn't highlighted** any color
> 10. The bubble with a 7 number inside(~44.4Kbp) **is partially highlighted** in red color

7. **FIXED**: We've got 2 items - "bubble" of two variants [1] and a single variant [2]; since we don't known bubble [1] coloring info, we will render *partially highlighted* bubble with single variant [2] color;
8. **NOT FIXED**: Again, we've got 2 items - "bubble" of four variants and a single variant; we're highlighting the bubble by the color we known (of the single variant);
9. **NOT FIXED**: We've got a single bubble without* coloring info;
10. **NOT FIXED**: the same as 8.
 
_______
*Actually, when we get a bubble from the API, we *do* know *some* highlighting info: we have `info` fields of *some* variant inside it. So, we've also fixed our highlighting rendering to respect this single variant inside a bubble (in case if it hits some highlighting profile)

**Comment by Tatyana2022** [comment]
Fixed and verified
