### ISSUE TITLE
BUG: Errors are displayed in the console when opening certain .gff files

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#490]
**Preconditions:**
1. Open NGB
2. Open Console (F12)

**To Reproduce**

1. Go to 'Datasets' panel
2. Select _second_ dataset with .gff files
3.  Look at Console

**Expected behavior**
_Second_ dataset is selected. No errors in the console

**Actual result**
Second dataset is selected. 
The following error displays in the console: 
`:8080/catgenome/#/CP…:%22GENE%22%7D%5D:1 Uncaught (in promise) {message: "Your operation has been aborted due to NGB has encountered a server problem.", status: "ERROR"}`

**Environment:**
 - NGB version: 2.6.1.2585
 - Browser: Chrome Version 91.0.4472.114

**Comment by mzueva** [comment]
@rodichenko @DmitriiKrasnov  Problem is caused by reference without gene annotation files attached. I'll fix error on the server to prevent error and return empty request, but we also need to fix the following on client-side:
1. Do not send gene table requests when reference has no annotation files attached and no gene files are selected in the dataset
2. When some gene files are selected in the dataset, its ids shall be passed as `geneFileIdsByProject`, e.g.:
```
{
  "pageSize": 5,
  "geneFileIdsByProject": {"97": [ 65]}
}
```
Where `97` is dataset id, and `65` is gene file `id` (not `bioDataItemId`)

**Comment by Tatyana2022** [comment]
***Fixed and Verified***
