### ISSUE TITLE
Error occurs when run NGB v.2.5.1 over NGB v.2.5.0: Migration Checksum mismatch for migration.

### ISSUE THREAD

**Issue by Dmitrii-Romanov** [epam/NGB#88]
Initial situation:
•	CentOS Linux release 7.3.1611 (Core), Total RAM: 3780884  
•	There is running /opt/ngb/catgenome-2.5.jar (loaded from http://ngb.opensource.epam.com/distr/2.5/, file size – 93566412, file date - Jul  5 12:07) with some registered datasets.

Version upgrade actions:
•	Run /opt/ngb/catgenome-latest.jar (loaded from http://ngb.opensource.epam.com/distr/latest/, file size – 93531271, file date - Sep 28 01:09). I.e. running new NGB version in the same folder, over existing H2 and contens folders/files 

Result:
•	ERROR [28/09/2017 18:18:33][main][org.springframework.boot.SpringApplication] Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [conf/catgenome/applicationContext-flyway.xml]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 2016.11.21.17.58

Output and log files attached.
[2017-09-28 NGB run fail output.txt](https://github.com/epam/NGB/files/1341543/2017-09-28.NGB.run.fail.output.txt)
[catgenome-error.log](https://github.com/epam/NGB/files/1341542/catgenome-error.log)

**Comment by mzueva** [comment]
@Dmitrii-Romanov, unfortunately version 2.5 and the latest 2.5.1 really have problem with db migration and we've prepared a script to fix this issue, please find it in the attachment to this comment.
The archive **migration_fix.zip** contains SQL script **checksum.sql** for fixing migration in DB and shell script **fix_migration.sh** to run it. 
In order to launch SQL script, you can use H2 console, if you have one installed (make sure that NGB is not running while you are connecting to it's DB using console).
Otherwise follow this instruction:
1. Download and unpack **migration_fix.zip**
2. Download H2 driver [(h2.jar)](http://repo2.maven.org/maven2/com/h2database/h2/1.3.176/h2-1.3.176.jar)
3. Shut down NGB server
4. Change directory to the unpacked **migration_fix** folder and run **fix_migration.sh** with two input arguments: path to H2 driver and path to NGb installation folder, e.g.:
`fix_migration.sh /home/downloads/h2-1.3.176.jar /opt/NGB`

After applying the script 2.5.1 will start on top of previous 2.5 installation

[migration_fix.zip](https://github.com/epam/NGB/files/1344452/migration_fix.zip)

**Comment by Dmitrii-Romanov** [comment]
@mzueva, thanks for fixing the problem.  Your scenario and script works.
